name = "Gtool3"
uuid = "fda5157c-64ce-41e4-a54e-cecf46bc244d"
authors = ["Chihiro Kodama"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
